#%RAML 1.0 Library
types:
    employees:
      type: array
      items: employee
    employee:
      type: object
      properties:
        id:  number        
        employee_name: string
        employee_salary: number
        employee_age: number
      
        
