#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/3b74a539-8978-4f25-a95b-e87ca1411f39/ # 
version: v1
title: db-demo
uses:
  employee: datatypes/empdatatype.raml
traits:
  clienttarits: !include traits/trait.raml

/employee:
  post:
    is: [clienttarits]
    body: 
      application/json:
        type: employee.employee
        example:  !include  examples/empexample.json
    responses:
      201:
        body:
          application/json: 
            type: employee.employee
            example:  !include  examples/empexample.json
